/*
 * Comm.c
 *
 *  Created on: May 4, 2024
 *      Author: abdel
 */

// comm_module.c
#include "Comm.h"

// Private variables
extern UART_HandleTypeDef huart1;
// You'll need to define CAN_HandleTypeDef if you haven't already

// Private functions
static void UART_Init(void)
{
	// UART initialization code generated by STM32CubeMX
	// Customize this according to your UART configuration
	huart1.Instance = USART1;
	huart1.Init.BaudRate = 9600;
	huart1.Init.WordLength = UART_WORDLENGTH_8B;
	huart1.Init.StopBits = UART_STOPBITS_1;
	huart1.Init.Parity = UART_PARITY_NONE;
	huart1.Init.Mode = UART_MODE_TX_RX;
	huart1.Init.HwFlowCtl = UART_HWCONTROL_NONE;
	huart1.Init.OverSampling = UART_OVERSAMPLING_16;
	if (HAL_UART_Init(&huart1) != HAL_OK)
	{
		//Error_Handler();
	}
}

static void CAN_Init(void)
{
	// CAN initialization code generated by STM32CubeMX
	// Customize this according to your CAN configuration
}

// Public functions

void Comm_Init(Comm_Interface interface)
{
	if (interface == COMM_UART)
	{
		UART_Init();
	}
	else if (interface == COMM_CAN)
	{
		CAN_Init();
	}
}

HAL_StatusTypeDef Comm_Publish(Comm_Interface interface, uint8_t *data, uint16_t length)
{
	HAL_StatusTypeDef HAL_CommError = HAL_OK;
	if (interface == COMM_UART)
	{
		HAL_CommError = HAL_UART_Transmit(&huart1, data, length, HAL_MAX_DELAY);
	}
	else if (interface == COMM_CAN)
	{
		// Implement CAN transmission
	}
	return HAL_CommError;
}

HAL_StatusTypeDef Comm_Collect(Comm_Interface interface, uint8_t *buffer, uint16_t length)
{
	HAL_StatusTypeDef HAL_CommError = HAL_OK;

	if (interface == COMM_UART)
	{
		HAL_CommError = HAL_UART_Receive(&huart1, buffer, length, HAL_MAX_DELAY);
	}
	else if (interface == COMM_CAN)
	{
		// Implement CAN reception
	}
	return HAL_CommError;
}
